"""add column students in meeting

Revision ID: 086d017b33fd
Revises: 110eb3732122
Create Date: 2022-07-01 16:21:24.997633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '086d017b33fd'
down_revision = '110eb3732122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('students', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting', 'students')
    # ### end Alembic commands ###
