"""empty message

Revision ID: 110eb3732122
Revises: cc8ddb658501
Create Date: 2022-07-01 09:11:32.297409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '110eb3732122'
down_revision = 'cc8ddb658501'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'participant_student', ['id'])
    op.create_unique_constraint(None, 'student', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='unique')
    op.drop_constraint(None, 'participant_student', type_='unique')
    # ### end Alembic commands ###
