"""empty message

Revision ID: 23e303bcc82a
Revises: 635f1877200c
Create Date: 2022-06-30 17:48:23.090890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23e303bcc82a'
down_revision = '635f1877200c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('capacity', sa.Integer(), nullable=False))
    op.drop_column('room', 'person_num')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('person_num', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('room', 'capacity')
    # ### end Alembic commands ###
