"""add column is_confirmed in Meeting

Revision ID: 30835a97aade
Revises: c9dc7df2f67e
Create Date: 2022-06-29 14:22:51.647348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30835a97aade'
down_revision = 'c9dc7df2f67e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('is_confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting', 'is_confirmed')
    # ### end Alembic commands ###
