"""empty message

Revision ID: 635f1877200c
Revises: 055fe8246512
Create Date: 2022-06-30 17:46:54.616823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635f1877200c'
down_revision = '055fe8246512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting', sa.String(length=64), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meeting'], ['meeting.title'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('room', sa.Column('capacity', sa.Integer(), nullable=False))
    op.drop_column('room', 'person_num')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('person_num', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('room', 'capacity')
    op.drop_table('participants_user')
    # ### end Alembic commands ###
