"""empty message

Revision ID: 6e00370faba3
Revises: 30835a97aade
Create Date: 2022-06-29 16:51:16.970886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e00370faba3'
down_revision = '30835a97aade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('meeting_title_key', 'meeting', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('meeting_title_key', 'meeting', ['title'])
    # ### end Alembic commands ###
