"""empty message

Revision ID: 9e9bed5ab7c5
Revises: fe5bfcc6fc70
Create Date: 2022-06-28 12:37:04.886120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e9bed5ab7c5'
down_revision = 'fe5bfcc6fc70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'meeting', ['id'])
    op.create_unique_constraint(None, 'team', ['id'])
    op.add_column('user', sa.Column('teamId', sa.Integer(), nullable=False))
    op.drop_constraint('user_team_id_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'team', ['teamId'], ['id'])
    op.drop_column('user', 'team_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_team_id_fkey', 'user', 'team', ['team_id'], ['id'])
    op.drop_column('user', 'teamId')
    op.drop_constraint(None, 'team', type_='unique')
    op.drop_constraint(None, 'meeting', type_='unique')
    # ### end Alembic commands ###
