"""empty message

Revision ID: aa5195c27da2
Revises: 23e303bcc82a
Create Date: 2022-06-30 17:54:11.032547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa5195c27da2'
down_revision = '23e303bcc82a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('capacity', sa.Integer(), nullable=True))
    op.drop_column('room', 'person_num')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('person_num', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('room', 'capacity')
    # ### end Alembic commands ###
