"""empty message

Revision ID: c9dc7df2f67e
Revises: 3b5622b61017
Create Date: 2022-06-28 20:36:24.510723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9dc7df2f67e'
down_revision = '3b5622b61017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('teamId', sa.Integer(), nullable=True))
    op.add_column('meeting', sa.Column('bookerId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'meeting', 'user', ['bookerId'], ['id'])
    op.create_foreign_key(None, 'meeting', 'team', ['teamId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meeting', type_='foreignkey')
    op.drop_constraint(None, 'meeting', type_='foreignkey')
    op.drop_column('meeting', 'bookerId')
    op.drop_column('meeting', 'teamId')
    # ### end Alembic commands ###
